FROM python:3.9-slim

WORKDIR /app

RUN pip install tensorflow-cpu==2.7.0 "protobuf<3.21" "numpy<2.0" fastapi uvicorn pydantic prometheus-fastapi-instrumentator

COPY ./output/serving_model /app/output/serving_model
COPY app.py /app/app.py

CMD ["python", "app.py"]