FROM python:3.9-slim

WORKDIR /app

RUN pip install tensorflow-cpu fastapi uvicorn pydantic prometheus-fastapi-instrumentator

COPY ./output/serving_model /app/output/serving_model
COPY app.py /app/app.py

CMD ["python", "app.py"]